---
- name: Validate VyOS configuration file content
  hosts: localhost
  gather_facts: no

  vars:
    vlans:
      - id: 100
        name: "KISULI"
        vyos_ip: "10.10.100.11/24"

  tasks:
    - name: Read generated VyOS configuration file
      slurp:
        src: backup/output/vyos2_vyos-router_new.conf
      register: vyos_config_raw

    - name: Convert VyOS configuration to string
      set_fact:
        vyos_config: "{{ vyos_config_raw.content | b64decode }}"

    - name: Assert VyOS commands validity
      assert:
        that:
          - "'set interfaces bridge br0 vif {{ item.id }} address {{ item.vyos_ip }}' in vyos_config"
          - "'set interfaces bridge br0 vif {{ item.id }} description \"{{ item.name }}\"' in vyos_config"
          - "'set interfaces bridge br0 member interface eth2 allowed-vlan {{ item.id }}' in vyos_config"
          - "'set interfaces bridge br0 member interface eth3 allowed-vlan {{ item.id }}' in vyos_config"
        msg: "Invalid command found in VyOS configuration for VLAN {{ item.id }}."
      loop: "{{ vlans }}"

    - name: Validate IP address format for VyOS
      assert:
        that:
          - item.vyos_ip is match('^([0-9]{1,3}\\.){3}[0-9]{1,3}/[0-9]{1,2}$')
        msg: "Invalid VyOS IP address format for VLAN {{ item.id }}: {{ item.vyos_ip }}"
      loop: "{{ vlans }}"
